V1.5 unique ids for tasks
josheide/todoapp pull request #5
Opened 2023-05-10 12:02 UTC by josheide

Add an identifier field to the tasks. It can be taken from a counter (first task is 1, second is 2). The ID should be generated by the program and not the user. ✓
Modify the list command so it shows the IDs of the tasks ✓
Modify the add command so it always shows what ID was used for the new task. ✓
Modify the delete and complete commands so they take the ID of the task instead of its name.✓
Think about the users who update from the previous version of your program. Their stored file will be in the previous format. Make sure not to break anything for them and provide a nice migration process to this new version.✓

2023-05-10 23:07 UTC, balazskiss commented on src/Main.java
>              if (userInput.equals("add")) {
add command should not accept empty task name

2023-05-10 23:13 UTC, balazskiss commented on src/Main.java
> +                    System.out.println(userTask + " has been added with the unique identifier: " + taskList.size()); // If you delete a task then the ID that it prints here is off. I tried nextID her
The output here seems incorrect. When I add a task it reports a unique ID but then in the `list` command output I see a different ID.
This is a bug.

2023-05-10 23:13 UTC, balazskiss commented on src/Task.java
> +    Task(int id, String name, boolean isComplete, String assignedToUser) {
seems like the id parameter is unused here?

2023-05-10 23:13 UTC, balazskiss commented on src/Task.java
> +    Task(int id, String name, boolean isComplete, String assignedToUser) {
if it's unused it should not be there.

2023-05-10 23:15 UTC, balazskiss commented on src/Main.java
> +        int nextID = taskList.size() + 1;
nextID is in two places now: 1) here and 2) in Task class as a static variable. Thee two values can get out of sync which leads to bugs in the program.
I recommend to simplify this and have a single source of truth for nextID.

2023-05-10 23:16 UTC, balazskiss commented on src/Main.java
> +import java.io.*; // I replaced .File .FileReader .BufferedReader .BufferedWriter .FileWriter .IOException with *
No need to leave this comment in the code.

2023-05-10 23:16 UTC, balazskiss requested changes
there are some bugs to be squashed :)

2023-05-11 13:07 UTC, josheide commented on src/Main.java
> +                    System.out.println(userTask + " has been added with the unique identifier: " + taskList.size()); // If you delete a task then the ID that it prints here is off. I tried nextID her
This was a really tricky one to solve but I think I figured it out!

2023-05-11 13:07 UTC, josheide commented on src/Main.java
>              if (userInput.equals("add")) {
Got it!

2023-05-11 13:10 UTC, josheide commented on src/Task.java
> +    Task(int id, String name, boolean isComplete, String assignedToUser) {
Replaced it with nextId that I actually use.

2023-05-11 13:20 UTC, josheide commented on src/Main.java
> +import java.io.*; // I replaced .File .FileReader .BufferedReader .BufferedWriter .FileWriter .IOException with *
I just left it here in case this broke my code so that I would remember what to re-add :D

2023-05-15 09:22 UTC, balazskiss approved these changes

2023-05-15 09:22 UTC, balazskiss approved these changes

2023-05-15 09:22 UTC, balazskiss approved these changes

2023-05-15 09:22 UTC, balazskiss approved these changes

2023-05-15 09:22 UTC, merged